camera_viewer:
  ros__parameters:
    camera_sources:
      - /dev/video0
      - /dev/video1
      - /dev/video2
      - /dev/video3
      - /dev/video4
      - /dev/video5
      - /dev/video6
      - /dev/video7
      - /dev/video8
      - /dev/video9
    selected_camera: 0

